### ISSUE TITLE
About Mobs and Pushable Entities(Minecart etc) and Rideable&Controllable Entities(Boat etc)

### ISSUE THREAD

**Issue by GoodLucky777** [tim03we/FuturePlots#10]
Can you add a feature like when you spawn mobs (MobPlugin) in your plot, mob can't go outside of your plot. (Mob border system) Can you add this feature? I think it will need when I use MobPlugin together.
Also, this issue happen with pushable entities or ride&control able entities.

**Comment by tim03we** [comment]
Unfortunately, it is currently not possible for mobs to remain on their properties, as Nukkit does not record the movement of animals. But I will keep this feature in mind.
