### ISSUE TITLE
No Registered Permission

### ISSUE THREAD

**Issue by GoodLucky777** [tim03we/FuturePlots#12]
I think there is no code that register permission. I think #11 error is because of this.

Also Luckperms doesn't detect permission called "futureplots.command.generate".

**Comment by tim03we** [comment]
There may be a connection with Synpase or Nemisys why it does not work. If you don't use Nemisys, LuckPerms works fine. 
![image](https://user-images.githubusercontent.com/38113441/83019398-2dc0cc00-a027-11ea-977e-f01ca0eb6a86.png)

**Comment by GoodLucky777** [comment]
okay, thanks
