### ISSUE TITLE
Mob Explosion Problem

### ISSUE THREAD

**Issue by GoodLucky777** [tim03we/FuturePlots#14]
MobPlugin's creeper explosion can break other plots, path, border.

**Comment by tim03we** [comment]
When I tested it, even mobs didn't destroy the streets, borders. :thinking:

**Comment by tim03we** [comment]
Please take a look at this video.
https://youtu.be/CXBoM2sMou8

**Comment by tim03we** [comment]
This issue will be closed as this issue is already discussed in another issue.
