### ISSUE TITLE
Nemisys Problem

### ISSUE THREAD

**Issue by GoodLucky777** [tim03we/FuturePlots#15]
I use latest FuturePlots.
Image:
![Screenshot_20200526-133010_Minecraft](https://user-images.githubusercontent.com/43497313/82860630-35b03b80-9f55-11ea-8627-514109370757.jpg)

Related Issue: #9

**Comment by tim03we** [comment]
I'll look at it later.

**Comment by tim03we** [comment]
Please take a look at this video.
https://youtu.be/FfVwTo18PiM

**Comment by GoodLucky777** [comment]
> Please take a look at this video.
> https://youtu.be/FfVwTo18PiM

Oh.. My server user said it was ender crystal explosion. Another user report bug to me it was because of TNT not an ender crystal. Sorry.

**Comment by tim03we** [comment]
It's the same there. Nothing is destroyed. 
https://youtu.be/ONTjdlwF9iA

**Comment by tim03we** [comment]
Is it possible that you still have the old version? The latest version is the 1.2.4-SNAPSHOT.

**Comment by GoodLucky777** [comment]
> Is it possible that you still have the old version? The latest version is the 1.2.4-SNAPSHOT.

No i am using 1.2.4

**Comment by tim03we** [comment]
Then why does it work for me and not for you? Is your world even still recognized as a plot world?

**Comment by GoodLucky777** [comment]
> Then why does it work for me and not for you? Is your world even still recognized as a plot world?

Does Nemisys affect this plugin? I'm using Nemisys - SynapseAPI.

**Comment by tim03we** [comment]
It's possible. Anything else that affects Nukkit, I can't prevent. I myself recommend Waterdog instead of Nemisys.

**Comment by GoodLucky777** [comment]
> It's possible. Anything else that affects Nukkit, I can't prevent. I myself recommend Waterdog instead of Nemisys.

Is this Nemisys bug or because of difference api between Nukkit and Nemisys?

**Comment by tim03we** [comment]
It should be Nemisys.  Seeing him like that in the video, it works for me.
