### ISSUE TITLE
Suggestion: /plot fix

### ISSUE THREAD

**Issue by GoodLucky777** [tim03we/FuturePlots#16]
Can you add a feature that regenerate broken path and borders like adding command like /plot fix?

**Comment by tim03we** [comment]
I recommend the plugin here.  With the plugin you can regenerate broken chunks back to the source.
https://nukkitx.com/resources/chunkreset.207

**Comment by GoodLucky777** [comment]
> I recommend the plugin here. With the plugin you can regenerate broken chunks back to the source.
> https://nukkitx.com/resources/chunkreset.207

I was suggesting about fixing command that fix(regenerate) border and path things. Chuck reset reset whole chunk so it will delete also plot.

**Comment by tim03we** [comment]
What do you mean with "path things"?

**Comment by GoodLucky777** [comment]
> What do you mean with "path things"?

https://github.com/tim03we/FuturePlots/blob/2e98ff7636f55cf8cfac9be6953a37f0976efd91/src/main/resources/config.yml#L27

**Comment by tim03we** [comment]
Since this is no longer happening so quickly. The road being ruined by TNT will not happen as quickly in the future because this problem has been fixed. But I keep it in mind that this command might come one day, but right now there are more important things. I ask for your understanding.

**Comment by GoodLucky777** [comment]
> Since this is no longer happening so quickly. The road being ruined by TNT will not happen as quickly in the future because this problem has been fixed. But I keep it in mind that this command might come one day, but right now there are more important things. I ask for your understanding.

Thank you!
