### ISSUE TITLE
Suggestion: Nemisys Support

### ISSUE THREAD

**Issue by GoodLucky777** [tim03we/FuturePlots#20]
I think it will be great!

**Comment by tim03we** [comment]
I will deal with nemisys the days, if I find the time.

**Comment by GoodLucky777** [comment]
Thank you!

**Comment by tim03we** [comment]
In the background you can see how the Nukkit server runs with Nemisys. As you can also see in the video, TNT and other explosions work fine.
https://www.youtube.com/watch?v=6SiKlXQJ3gM

**Comment by GoodLucky777** [comment]
It works fine now. Thanks
