### ISSUE TITLE
ISSUE: Players unable to claim plots

### ISSUE THREAD

**Issue by SilentBlade1472** [tim03we/FuturePlots#21]
In-game when a Player tries claiming a plot an error occurs on all plots saying "FuturePlots > This plot has already been claimed" Even if the plot has never been claimed. Console shows no error either.

**Comment by tim03we** [comment]
With which plugin version did this happen?

**Comment by tim03we** [comment]
The bug has now been fixed in version 1.2.7-SNAPSHOT.
