### ISSUE TITLE
/plot clear doesn't remove some Entity Things

### ISSUE THREAD

**Issue by GoodLucky777** [tim03we/FuturePlots#28]
### Issue description

- What happened? How did it happen?
/plot clear can't remove Paint, Ender crystal, Item things.
### Steps to reproduce the issue

1. /plot clear

### Version and Provider

* FuturePlots: 1.2.7.3
* Provider: yaml

### Steps before you create the issue 

- If you remove all other plugins, does the issue still occur?
yes
- Have you ever tried the bug as an OP and as a non-OP player?
yes

**Comment by tim03we** [comment]
Will be fixed in the next update.  ;)
