### ISSUE TITLE
/plot clear doesn't remove Ender Crystal

### ISSUE THREAD

**Issue by GoodLucky777** [tim03we/FuturePlots#29]
### Issue description

- What happened? How did it happen?
/plot clear doesn't remove Ender Crystal.
### Steps to reproduce the issue

1. /plot clear

### Version and Provider

* FuturePlots: 1.2.7.3
* Provider: yaml

### Steps before you create the issue 

- If you remove all other plugins, does the issue still occur?
yes
- Have you ever tried the bug as an OP and as a non-OP player?
yes

### Crashdump, backtrace or other files
```
-
```

**Comment by tim03we** [comment]
Since the Ender Crystal is an entity, it belongs to issue #28 , so I will close this issue.

**Comment by GoodLucky777** [comment]
Merge this issue with #28 .
