### ISSUE TITLE
Can you make command usage can be translated?

### ISSUE THREAD

**Issue by GoodLucky777** [tim03we/FuturePlots#32]
### Issue description
Can you make command usage can be translated? It will be useful for non-English servers.

(This is not a bug, I forgot to use Blank Issue template.)

**Comment by dongmin-dev** [comment]
https://github.com/aesoppppp/FuturePlots

I update Korean translatiom from every update.
It has Korean commands too with /땅 command

**Comment by GoodLucky777** [comment]
> https://github.com/aesoppppp/FuturePlots
> 
> I update Korean translatiom from every update.
> It has Korean commands too with /땅 command

But problem is Forked version so it can be hard to maintain all project per languages.

**Comment by dongmin-dev** [comment]
> > https://github.com/aesoppppp/FuturePlots
> 
> > 
> 
> > I update Korean translatiom from every update.
> 
> > It has Korean commands too with /땅 command
> 
> 
> 
> But problem is Forked version so it can be hard to maintain all project per languages.

So what I can do this all day 😂😂
Or you can

**Comment by GoodLucky777** [comment]
> > > https://github.com/aesoppppp/FuturePlots
> > 
> > 
> > > 
> > 
> > 
> > > I update Korean translatiom from every update.
> > 
> > 
> > > It has Korean commands too with /땅 command
> > 
> > 
> > But problem is Forked version so it can be hard to maintain all project per languages.
> 
> So what I can do this all day 
> Or you can

Probably it will be better when able to translate command usage, able to change command(/plot) and parameters.

**Comment by tim03we** [comment]
In the next update it will be possible to edit the commands completely.

**Comment by tim03we** [comment]
The update is now out.
https://nukkitx.com/resources/futureplots.457/

**Comment by GoodLucky777** [comment]
> The update is now out.
> https://nukkitx.com/resources/futureplots.457/

Thank you!
