### ISSUE TITLE
Can you make give owner permission to someone command?

### ISSUE THREAD

**Issue by GoodLucky777** [tim03we/FuturePlots#33]
Can you make give owner permission to someone command? Like giving the plot's owner permission to someone. It will be useful.

**Comment by tim03we** [comment]
Do you mean the /plot setowner command or such admin permissions like PlotSquared to be able to interact on plots although you are not the owner of the plot?

**Comment by GoodLucky777** [comment]
Like plot A is my plot. And I don't have any OP permission. And I want to give plot A owner permission to someone. /plot giveowner maybe?

**Comment by tim03we** [comment]
That's what I mean by /p setowner. ;)

**Comment by tim03we** [comment]
The update is now available for the github releases. It will also be available soon on the NukkitX page. 
https://github.com/tim03we/FuturePlots/releases/tag/1.3.2-SNAPSHOT
