### ISSUE TITLE
Parameters Disappear (command usage when I typing command on chat)

### ISSUE THREAD

**Issue by GoodLucky777** [tim03we/FuturePlots#34]
### Issue description

- What happened? How did it happen?
It disappear after command usage can be customized update.
### Steps to reproduce the issue

1. type /plot
2. there will be no usage tip things

### Version and Provider

* FuturePlots: 1.3.2
* Provider: yaml

### Steps before you create the issue 

- If you remove all other plugins, does the issue still occur?
yes
- Have you ever tried the bug as an OP and as a non-OP player?
yes

### Crashdump, backtrace or other files
```
No Crash
```

**Comment by Aenoxic** [comment]
@good777LUCKY 
Can you attach a screenshot or at best a video to the bug to help identify which bug it is?

**Comment by GoodLucky777** [comment]
For example, command like /gamerule, it will show gray usages above text(chat) input box. But /plot doesn't show sub-commands usage above text(chat) input box. But it was appear before 1.3.0.

**Comment by tim03we** [comment]
With the normal configuration it works fine. After that I tried it with your configuration and it did not work. I strongly suspect that Nukkit does not support these characters and there is nothing I can do about it, so I will close this issue.
