### ISSUE TITLE
FuturePlots errors

### ISSUE THREAD

**Issue by unknowghostlife** [tim03we/FuturePlots#35]
13:43:34 [FATAL] [FuturePlots] The version of the language configuration does not match. You will find the old file marked "eng_old.yml" in the same language directory.
13:43:34 [FATAL] [FuturePlots] The version of the configuration does not match. You will find the old file marked "config_old.yml" in the same directory.
13:43:34 [FATAL] [FuturePlots] The version of the commands file does not match. You will find the old file marked "commands_old.yml" in the same directory.
13:43:34 [ERROR] [FuturePlots] Plugin FuturePlots v1.4.0 has failed to register events for class tim03we.futureplots.listener.BlockPiston because cn/nukkit/event/block/BlockPistonEvent does not exist.
idk why it does this

**Comment by tim03we** [comment]
In the new version some things have changed, so there is a new version of the language, commands and config file and it has been updated. Adjust the new files and you will have no further problems.

**Comment by unknowghostlife** [comment]
i have but i still get error

**Comment by tim03we** [comment]
Diesen hier? 
13:43:34 [ERROR] [FuturePlots] Plugin FuturePlots v1.4.0 has failed to register events for class tim03we.futureplots.listener.BlockPiston because cn/nukkit/event/block/BlockPistonEvent does not exist.
idk why it does this

**Comment by unknowghostlife** [comment]
and i dont get config file from this

**Comment by unknowghostlife** [comment]
and that all i get from the server log i dont crash but when i type plugins it doesnt show

**Comment by unknowghostlife** [comment]
it name or commands

**Comment by tim03we** [comment]
Can you send me the log?
https://workupload.com

**Comment by tim03we** [comment]
I sent you a friend request on Discord.

**Comment by tim03we** [comment]
Will be solved in private on Discord.
