### ISSUE TITLE
[Question] Will FuturePlots support PowerNukkit?

### ISSUE THREAD

**Issue by GoodLucky777** [tim03we/FuturePlots#37]
Will FuturePlots support PowerNukkit?

**Comment by tim03we** [comment]
FuturePlots will only support Nukkit:master for the first time. Whether it also works with PowerNukkit, you have to try it.

**Comment by GoodLucky777** [comment]
I have some NPE error.
![Screenshot_20200628-154527_Samsung Internet](https://user-images.githubusercontent.com/43497313/85940573-2fe4b600-b958-11ea-9d5d-915643a89264.jpg)

**Comment by tim03we** [comment]
Told you i wasnt't gonna support the PowerNukkit

**Comment by GoodLucky777** [comment]
So, it will not support forever or it will be supported somedays? (Just a question )

**Comment by tim03we** [comment]
If I were to make a spontaneous statement now, I would say no, since I only supported the official software of NukkitX.

**Comment by GoodLucky777** [comment]
Thank you for replying this question.
