### ISSUE TITLE
Restart Plot Owner Bug

### ISSUE THREAD

**Issue by MonoAdrian23** [tim03we/FuturePlots#38]
### Issue description

- Each player has claimed a plot but after Server restart, this plots have no Plot owners

### Steps to reproduce the issue

1. ... Claim a Plot
2. ... Restart the Server
3. ... This plot is disposed

### Version and Provider

* FuturePlots: 1.4.3 Snapshot
* Provider: PowerNukkit Latest

### Steps before you create the issue 

- If you remove all other plugins, does the issue still occur? [Yes]
- Have you ever tried the bug as an OP and as a non-OP player?
Player 

### Crashdump, backtrace or other files
```
Insert here the error that appears in the console. Make sure that the debug mode of Nukkit is active [Is active, no Crashdumps]
```

**Comment by tim03we** [comment]
Unfortunately, I currently do not support forks from other developers. I am sorry. But in the near future there will be support for PowerNukkit.

**Comment by MontnDev** [comment]
> 
> 
> Unfortunately, I currently do not support forks from other developers. I am sorry. But in the near future there will be support for PowerNukkit.

when?

**Comment by MonoAdrian23** [comment]
Nukkit is down!
Each Fork of Nukkit is better.
PowerNukkit Supports Nukkit for Updates.
Nukkit 2.0 Development is implemented in PowerNukkit.

I think, you should Plotsquared.
This Plugin have's to much Bugs and Plotsquared works great.
