### ISSUE TITLE
plot xuid support request

### ISSUE THREAD

**Issue by BroccoliGG** [tim03we/FuturePlots#44]
Could you add support for using UUID instead of player names for plots?
There is a uuid entry in config.yml, but it is not yet complete and not functional.

I need this feature because the added support for UUID will allow players to keep their plots after changing their gamertag.

```yaml
# NOT COMPLETED!
# Should the UUID be used to keep the plot when changing the player name
uuid: true
```

**Comment by tim03we** [comment]
Currently being clarified via Discord.

**Comment by tim03we** [comment]
We are getting closer to the goal and XUID support will find its place in the coming weeks.

**Comment by tim03we** [comment]
Released
