### ISSUE TITLE
Players plant tree leaves that will grow out of the ground

### ISSUE THREAD

**Issue by jlhsr** [tim03we/FuturePlots#46]
### Issue description

- What happened? How did it happen?
Players plant tree leaves that will grow out of the ground
### Steps to reproduce the issue

1. Plant trees at the edge of the field and speed up ripening

### Version and Provider

* FuturePlots:FuturePlots-2.0.4-SNAPSHOT
![G123 YCJO9YOWI1)3$RVY6P](https://user-images.githubusercontent.com/22098995/187074227-5a13f6d3-20f9-447a-bb1b-2fc7be8bddc8.png)

**Comment by tim03we** [comment]
I understand the issue and try to fix the problem as soon as possible. Currently, the focus is on XUID support, if the gamertag is changed, that the plot still belongs to the player.

**Comment by tim03we** [comment]
You can find more details on our Discord. 
https://discord.gg/2PYGr7GfTf

**Comment by tim03we** [comment]
The bug is fixed and will be present in version 3.0.0-SNAPSHOT!

![Screenshot_1](https://user-images.githubusercontent.com/38113441/188269146-edbf76f5-8c12-4727-87a8-6adcf4aeb463.png)
