### ISSUE TITLE
Non-OP players can clean, delete, dispose the plot.

### ISSUE THREAD

**Issue by dongmin-dev** [tim03we/FuturePlots#7]
Non-OP players can clean, delete, dispose the users plot.

**Comment by dongmin-dev** [comment]
+ Non-OP players can't shoot arrows

**Comment by tim03we** [comment]
I'll take a look at it. Thanks for the report.

**Comment by tim03we** [comment]
The /p delete command is not affected. The other two commands are then fixed in 1.2.2-SNAPSHOT. The update will take place during the course of the day on NukkitX.

**Comment by dongmin-dev** [comment]
Ok thanks 🙏
And the bow shooting error is not from Futureplots?

**Comment by tim03we** [comment]
I'll check and let you know.

**Comment by tim03we** [comment]
It took a little longer than planned. The update will be available on NukkitX later today on 20.05.
