### ISSUE TITLE
Command No Permission Message: null

### ISSUE THREAD

**Issue by GoodLucky777** [tim03we/FuturePlots#8]
When I have no permission for executing some command, it will say "null".

**Comment by tim03we** [comment]
Which commands?

**Comment by GoodLucky777** [comment]
> Which commands?

/plot generate

**Comment by tim03we** [comment]
You need the permission futureplots.command.generate otherwise the output is null if you don't have enough rights.

**Comment by GoodLucky777** [comment]
> You need the permission futureplots.command.generate otherwise the output is null if you don't have enough rights.

Can you add a warning message like "You don't have enough permission."?

**Comment by tim03we** [comment]
Yeah, I can do that.  This will be included in the next major update.

**Comment by tim03we** [comment]
But the command works?

**Comment by GoodLucky777** [comment]
command is working

**Comment by tim03we** [comment]
Ok. :+1:
