### ISSUE TITLE
TNT Problem!

### ISSUE THREAD

**Issue by GoodLucky777** [tim03we/FuturePlots#9]
When I make many tnts on the plot and activate it, it will break wall and path! Can you prevent it?

**Comment by tim03we** [comment]
Yeah, I can do that. Just wait for the next upcoming update. And thanks for your report! 👍

**Comment by GoodLucky777** [comment]
> Yeah, I can do that. Just wait for the next upcoming update. And thanks for your report!

Also MobPlugin Creeper, Ghast explosion

**Comment by tim03we** [comment]
This error has now been fixed. I will now close the issue.
